# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fb0091e5b4bdf47f3b46c5a77a7b49baaeb34fb2c2b1ef4d27d23c34a0b225a93afebb3f402978fde73d5d16811880d188509ddda679738a84d018f607d868fe

test:
  secret_key_base: d4653adc37d9267fb2b74d998e454e735adff508b560c1d1839099dc5f60144d70b63ff2ab2088366f48cb85ec08f255eac6cf80f38957d3214e9c26534be70e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
